version: '3.8'

services:
  consul:
    image: consul:1.15.4
    container_name: consul-container
    ports:
      - "8500:8500"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      retries: 5

  config:
    build:
      context: ./Config
    container_name: config-service
    ports:
      - "8788:8788"
    expose:
      - "8788"
    environment:
      - CONSUL_HOST=consul-container
      - CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-service:8788/actuator/health"]
      interval: 10s
      retries: 10
      start_period: 30s  # Increase the time Docker will wait before starting health checks
      timeout: 5s

  gateway:
    build:
      context: ./Gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8788
      - CONSUL_HOST=consul-container
      - CONSUL_PORT=8500
    depends_on:
      config:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5

  client:
    build:
      context: ./Client
    container_name: client-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8788
      - CONSUL_HOST=consul-container
      - CONSUL_PORT=8500
    depends_on:
      config:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 5

  voiture:
    build:
      context: ./Voiture
    container_name: voiture-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - CONFIG_SERVICE_URL=http://config-service:8788
      - CONSUL_HOST=consul-container
      - CONSUL_PORT=8500
      - CLIENT_HOST=gateway-service
      - CLIENT_PORT=8080
    depends_on:
      client:
        condition: service_healthy
      gateway:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 5

networks:
  microservices-network:
    driver: bridge
